version: "3"
services:
  hapi-fhir-mysql:
    #platform: linux/x86_64
    image: mysql:latest
    container_name: hapi-fhir-mysql
    #https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html
    command: --lower_case_table_names=1
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]            
      interval: 20s
      timeout: 20s
      retries: 3
    environment:
      MYSQL_DATABASE: 'hapi'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    volumes:
      - hapi-fhir-mysql:/var/lib/mysql
  # hapi-fhir-jpaserver-start:
  #   build: .
  #   depends_on:
  #     - hapi-fhir-mysql
  #   container_name: hapi-fhir-jpaserver-start
  #   restart: on-failure
  #   ports:
  #     - "8080:8080"
volumes:
  hapi-fhir-mysql:
