version: "3"
services:
  hapi-fhir-postgres:
    container_name: "hapi-fhir-db"
    image: postgres:9.6
    volumes:
      - hapi_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-hapi}"]
      interval: 20s
      timeout: 20s
      retries: 3
    networks:
      - hapi-net-db
    ports:
      - "25435:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB:       hapi
      POSTGRES_USER:     hapi
      POSTGRES_PASSWORD: password
  # hapi-fhir-jpaserver-start:
  #   platform: linux/amd64
  #   build: .
  #   depends_on:
  #     - hapi-fhir-postgres
  #   container_name: hapi-fhir-jpaserver-start
  #   restart: on-failure
  #   ports:
  #     - "8080:8080"
volumes:
  hapi_data:

networks:
  hapi-net-db:
    driver: bridge